# File: .github/workflows/repo-sync.yml
name: sync-shaGuar-proxy_tools
on:
  schedule:
    - cron: '5 15 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-shaGuar-proxy_tools
jobs:
  repo-sync:
    env:
      PAT: ${{ github.event.client_payload.PAT || secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync shaGuar-proxy_tools
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Shawn1eong/Proxy-Tools.git"
          source_branch: "master"
          destination_branch: "main"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
