# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青自动阅读二

on:
  workflow_dispatch:
  schedule:
     - cron: '6 1-12/2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ5: ${{ secrets.YOUTH_READ5 }}
      YOUTH_READ6: ${{ secrets.YOUTH_READ6 }}
      YOUTH_READ7: ${{ secrets.YOUTH_READ7 }}
      YOUTH_READ8: ${{ secrets.YOUTH_READ8 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读五】'
        if: env.YOUTH_READ
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ5 }}

      - name: '运行 【中青看点自动阅读六】'
        if: env.YOUTH_READ2
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ6 }}
          
      - name: '运行 【中青看点自动阅读七】'
        if: env.YOUTH_READ3
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ7 }}
          
      - name: '运行 【中青看点自动阅读八】'
        if: env.YOUTH_READ4
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ8 }}
